import { Inter } from "next/font/google";
import "@rainbow-me/rainbowkit/styles.css";
import "./globals.css";
import SideBar from "@/components/SideBar/SideBar";
import NavBar from "@/components/NavBar/NavBar";
import { Providers } from "./providers";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="flex justify-between align-top ">
            <div>{/* <SideBar /> */}</div>
            <div>
              <NavBar />
            </div>
          </div>
          <div>{children}</div>
        </Providers>
      </body>
      <Script src="../path/to/flowbite/dist/flowbite.min.js"></Script>
    </html>
  );
}
