import { Inter } from "next/font/google";
import "./globals.css";
import SideBar from "@/components/SideBar/SideBar";

import Script from "next/script";
import { Web3Modal } from "@/utils/connection";
import NavBar from "@/components/NavBar/NavBar";

export const metadata = {
  title: "InsureFi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Web3Modal>
          <SideBar />
          <div className="p-4 sm:ml-64">
            <NavBar />
            {children}
          </div>
        </Web3Modal>
      </body>
      <Script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.js"></Script>
    </html>
  );
}
